# 拦拦我是一个截器🍍

> 业务开发中，避免不了要与后端接口打交道。

## 0⃣️ 这里先提出几个问题：

1. 是否可以对后端接口返回的数据进行**统一处理**？

2. 接口请求异常怎么处理，比如：接口请求超时？

## 1⃣️ 接口的统一处理

> 我们通常使用axios来发送接受请求，而axios为我们提供优秀便捷的**拦截器**，便于我们对**发送的请求**和**接受到的返回结果**进行统一处理。

### 1.1 axios发送的请求处理

> 1、可以重定义axios的get请求方式的参数名。</br>
> 2、可以统一定义处理不同请求方式下，传给服务器的内容格式。

``` js
    const instance = axios.create();

    instance.defaults.withCredentials = true; // 带上cookie

    // 请求的拦截器
    instance.interceptors.request.use(function (config) {
        if (config.method === 'get' && config.data && !config.params) {
            // 1、写接口时，无论get/post，参数统一用data （懒得区分，可能也没有什么用😷）
            // 请求时，在将get的参数赋值给params
            config.params = config.data;
        } else if (config.method === 'post' && config.data) {
            // 2、有时post请求方式，后端接受的格式是FormData（因后端接口而异）
            let formData = new FormData();
            Object.keys(config.data).forEach((key) => {
                formData.append(key, config.data[key]);
            });
            config.data = formData;
            config.headers = {'Content-Type': 'multipart/form-data'};
        }
        return config;
    }, function (error) {
        return Promise.reject(error);
    });
```

### 1.2 axios接受到的返回结果处理

``` js
    // 接受的拦截器
    instance.interceptors.response.use(function (response) {
        // 正常
        return response;
    }, function (error) {
        // 异常
        return Promise.reject(error);
    });
```

### 1.3 发送的请求和接受到的结果进一步处理

> 1、可以根据服务器返回的code进行不同的处理。

- 一般接口请求成功，后端会返回code：200（code的值需要前后端一起定义）。
- 注意：登入超时code会返回10001，但此时接口还是请求成功的（根据success：true得知），此时我们可以引导用户重新登陆（✏️：有时token过期，我们可以自动重新获取token）。
- code原本是没有意义的，但是通过前后端的提前定义使其变得有意义。

> 2、判断接受到的结果是否是异常流，更好的方法应该是通过判断success的值。</br>
> 3、我们可以通过code值来区分是前端操作不当导致报错，还是因为后端操作不当导致报错。

- 前端操作不当：缺少参数、参数格式不对等。此时，应该提示用户具体原因。
- 后端操作不当：数据库查询崩了等。此时，就只需告诉用户是系统错误即可（他们不需要知道太多～who care）。
- 前后端的操作不当，我们可以通过Promise.reject返回不同格式的值。前端不当返回正常error Object，后端不当返回 Error 格式错误。

``` js
    const resolveResponse = ({config, response}) => {
        let loginTimeout = parseInt(response.data.code) === 10001; // 是否登陆超时
        let apiIsSuccess = parseInt(response.data.code) === 200; // 是否是后台的系统错误（注意：要和后台约定，是前端传的参数的导致没有数据，code返回200）
        let returnDataSuccess = response.data.success; // 是否是异常流

        if (loginTimeout) {
            // 登录超时,请刷新页面重新登录
            console.error('登录超时,请刷新页面重新登录');
            response.data.msg = '登录超时，请重新登录';
            return Promise.reject(response.data);
        }
        // 为了兼容500，前端报错（有些后端打死不给我200，只能自己手动屏蔽）
        if (config.otherType) {
            if (parseInt(response.data.code) === 500) {
                if (config.otherType === 'upData') {
                    console.error(`前端错误 - 【${config.name}】 ${config.url}`);
                    return Promise.reject(response.data);
                }
            }
        }
        if (response.status !== 200) {
            // 接口没通（提示：系统错误, 请稍后再试）
            let err = new Error(`没有调通 -【${config.name}】 ${config.url}`);
            return Promise.reject(err);
        }
        if (!apiIsSuccess) {
            // 不是前端的错误，后端错误（提示：系统错误, 请稍后再试）
            let err = new Error(`后端错误 - 【${config.name}】 ${config.url}`);
            return Promise.reject(err);
        }
        if (!returnDataSuccess) {
            // 前端错误导致的异常流（提示toast:error）
            console.error(`前端错误 - 【${config.name}】 ${config.url}`);
            return Promise.reject(response.data);
        } else {
            // 正确的（返回：接受到的内容data.data）
            return Promise.resolve(response.data.data);
        }
    };

    const request = function (config) {
        return instance({
            ...config
        })
        .then(response => Promise.resolve({config, response}))
        .then(resolveResponse)
        .catch((err) => {
            if (err instanceof Error) {
                // 后端不当
                console.error(err);
                Toast.show({ info: '请求失败, 请稍后再试', duration: 2000});
            } else {
                // 前端不当（有二维码traceId提示）
                Toast.show({ info: err.msg, duration: 2000, traceId: err.traceId });
            }
            // 正常
            return Promise.reject(err);
        });
    };
```

> 上面的代码来自：
[销售订单项目中的路由拦截器实例地址🔗](https://git.souche-inc.com/guanghui/frontend/new-pc-order-management/blob/master/src/api/_instance.js)

## 2⃣️ 接口请求异常处理

### 2.1 请求超时

> 通常情况下当接口请求超时了，就会报错。</br>
> 但是，我们可以通过axios的response拦截器，重新请求失败的接口多次。

``` js
    axios.defaults.retry = 4; // 请求次数
    axios.defaults.retryDelay = 1000; // 请求的间隙

    axios.interceptors.response.use(
        // 正常
        undefined,
        // 异常
        function axiosRetryInterceptor(err) {
            var config = err.config;
            // 出现以下不重新请求接口：
            //      1. err 中无config
            //      2. 没有设置最多重复请求超时接口几次
            if(!config || !config.retry) return Promise.reject(err);

            // 初始化当前是第几次请求
            config.__retryCount = config.__retryCount || 0;

            // 检查是否已经是最大次请求了
            if(config.__retryCount >= config.retry) {
                // Reject with the error
                return Promise.reject(err);
            }

            // 设置当前是重新请求的第几次
            config.__retryCount += 1;

            // 间隔一段时间再请求接口
            var backoff = new Promise(function(resolve) {
                setTimeout(function() {
                    resolve();
                }, config.retryDelay || 1);
            });

            // 用之前的config再次请求接口
            return backoff.then(function() {
                return axios(config);
            });
        }
    );
```